<%@ page language="java" pageEncoding="UTF-8"%>
<%@ page contentType="text/html; charset=UTF-8"%>
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="/struts-tags" prefix="s"%>
<div class="modal fade" id="2fa-options-modal" tabindex="-1" role="dialog" aria-labelledby="options-label" aria-hidden="true" style="display: none;">
	<div class="modal-dialog">
		<div class="modal-content">
			<s:if test="isEnabled2FA">
				<div class="modal-header" style="height: 40px;">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h3 class="modal-title" id="options-label">2 Factor Authentication Options</h3>
				</div>
				<div class="modal-body">
					<h5>The 2 Factor Authentication is activated.</h5>
				</div>
				<div class="modal-footer">
					<button type="button" style="float: left;" class="btn" id="disable-2fa">Disable</button>
				</div>
			</s:if>
			<s:else>
				<div class="modal-header" style="height: 40px;">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h3 class="modal-title" id="options-label">2 Factor Authentication Options</h3>
				</div>
				<div class="modal-body">
					<h4>How to authenticate with Google Authenticator?</h4>
					<h5 style="margin-bottom: 5px;">Install the Google Authenticator app on your phone.<br />Open and configure Google Authenticator.</h5>
					<ul style="margin-bottom: 5px;">
						<li>In Google Authenticator, touch Menu and select "Set up account."</li>
						<li>Select "Scan a barcode."</li>
						<li>Use your phone's camera to scan this barcode.</li>
					</ul>
					<div id="qr_code"></div>
					<h5>Once you have scanned the barcode, enter the 6-digit verification code generated by the Authenticator app.</h5>
					<span class="error-msg"></span>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal" style="float: left;margin-top: 10px;">Close</button>
					<input type="text" id="code-input" placeholder="Enter the code" style="margin-top: 10px;" />
					<button type="button" class="btn btn-primary" id="activate-auth-submit">Activate</button>
				</div>
			</s:else>
		</div>
	</div>
</div>

<div class="modal fade" id="2fa-auth-modal" tabindex="-1" role="dialog" aria-labelledby="options-label" aria-hidden="true" style="display: none;">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header" style="height: 40px;">
				<!-- <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button> -->
				<h3 class="modal-title" id="options-label">2 Factor Authentication</h3>
			</div>
			<div class="modal-body">
				<h5>Enter the 6-digit verification code generated by the Authenticator app.</h5>
				<span class="error-msg"></span>
			</div>
			<div class="modal-footer">
				<input type="text" id="code-input" placeholder="Enter the code" style="margin-top: 10px;" />
				<button type="button" class="btn btn-primary" id="auth-code-submit">Submit</button>
			</div>
		</div>
	</div>
</div>